mitre/HTTP-Proxy-Servlet

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
src/test/java/org/mitre/dsmiley/httpproxy/ProxyServletTest.java

Attempts to work-around Issue #70 by clearing the Content-Length header prior to sending a redirect.

Clear Content-Length header when sending redirect to client.

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
src/test/java/org/mitre/dsmiley/httpproxy/ProxyServletTest.java

Reverts mitre/HTTP-Proxy-Servlet#71

Revert "Clear Content-Length header when sending redirect to client."

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
src/test/java/org/mitre/dsmiley/httpproxy/ProxyServletTest.java

Another attempt to solve #70 redirects with body response.

Rework redirect handling to allow non-empty responses from the back-end server.

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
src/test/java/org/mitre/dsmiley/httpproxy/ProxyServletTest.java

Attempt to solve part 3 of Issue #70.
When rewriting URL that point towards the target URI we replace the target URI base with the path to the Proxy Servlet, which should allow the client to request the specified back-end resource (including query and fragment) through the same Proxy Servlet.
Extended the test-case for redirect locations to try some more use cases.

Fix return url rewriting by rebuilding it.

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
src/test/java/org/mitre/dsmiley/httpproxy/ModifyHeadersProxyServletTest.java
src/test/java/org/mitre/dsmiley/httpproxy/ProxyServletTest.java

overridable methods for extending classes to implement logic relate headers copied from request to proxy request and from proxied request to servlet response.
These methods are convenient to remove authentication headers from requests

overridable methods for extending classes to modify header before request/response is done

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
src/test/java/org/mitre/dsmiley/httpproxy/ProxyServletTest.java

* Added "preserveHost" configuration to preserve the original Host
header from the browser
* Added "preserveCookies" configuration to preserve the original cookie
names from the browser
* Added X-Forwarded-Proto to be set along side X-Forwarded-For

Added new parameters to configure headers

---

pom.xml

Since both the library and all it's dependencies (httpclient is built with target set to 1.6) are compatible with Java 6, it should be safe to downgrade the source/target java version to 1.6.
Without this, I'm running into the following error when running on JDK6:
java.lang.UnsupportedClassVersionError: org/mitre/dsmiley/httpproxy/ProxyServlet : Unsupported major.minor version 51.0

Downgrade java version to 1.6

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java

use "[;,]" when split cookie string to match the situation there is no space between cookie in header

fix #110: getRealCookie() cannot work using com.sun.jersey.api.client.Client

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java

When attempted to use the _ProxyServlet_ in Google AppEngine, we encountered this error:
> java.net.ProxySelector is a restricted class. Please see the Google App Engine developer's guide for more details.
`java.lang.NoClassDefFoundError: java.net.ProxySelector is a restricted class. Please see the Google  App Engine developer's guide for more details.
at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:50)
at org.apache.http.impl.client.SystemDefaultHttpClient.createHttpRoutePlanner(SystemDefaultHttpClient.java:135)
at org.apache.http.impl.client.AbstractHttpClient.getRoutePlanner(AbstractHttpClient.java:698)
at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:831)
at …

Replaces usage of deprecated HttpClient API.

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java

The connection timeout is configurable as a init-param in the servlet configuration, but there is not an equivalent property for the read timeout (socketTimeout in the Apache HTTP Client library).
This a small change to put these property configurable in the web.xml file.

Configurable read timeout

---

CHANGES.md
pom.xml
src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java

HttpOnly flag is missed when copying proxy cookies to request client.

Copy HttpOnly flag in proxy cookie

---

CHANGES.md
src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java

The read timeout must be set in the SocketConfig as well.
Setting the read timeout only in the RequestConfig can cause hangs which
could block the whole proxy forever.

Setting the read timeout in the RequestConfig is not enough.

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java

The connection and read timeouts are configurable as a init-param in the servlet configuration, but there is not an equivalent property for the connection request timeout (the timeout in milliseconds used when requesting a connection from the connection manager).

Configurable Connection Request Timeout

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java

I'd like to allow redirects of URL with an encoded slash (%2F).
As mentioned in #34, one way of doing it is to use `getRequestURI` instead of `getPathInfo`.
It'd be great if you could do it in `org.mitre.dsmiley.httpproxy.ProxyServlet`, but would be still nice if its child class like the below example can do it themselves.
```
public class MyProxyServlet extends ProxyServlet {
/**
* Get undecoded version of servletRequest.getPathInfo()
*/
@Override
protected String rewritePathInfoFromRequest(HttpServletRequest servletRequest) {
String temp = servletRequest.getContextPath().concat( servletRequest.getServletPath() );
return servletRequest.getRequestURI().substring( temp.length() );
}
// Do not encode here because it is not decoded.
@Override
protected CharSequence …
```

Change ProxyServlet.encodeUriQuery to non-static so that it can be overridden

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java

In order to have more control for customized ProxyServlets to intervene HttpClient building as well as copying cookies, introduced more extension points.
This will for example help, if you want to create a HTTPS Certificate agnostic HttpClient as in mitre/HTTP-Proxy-Servlet#3.
The extension point for the `HttpClient` is required for adaptions like in mitre/HTTP-Proxy-Servlet#3, i. e. to add a customized SSLSocketFactory.
We required the extension point for copying cookies, in order to customize `servletCookie.setSecure(cookie.getSecure());` which we adjusted to:
```
servletCookie.setSecure("https".equals(servletRequest.getScheme()) && cookie.getSecure());
```

More Extension Points for ProxyServlet

---

.gitignore
CHANGES.md
pom.xml
src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
src/test/java/org/mitre/dsmiley/httpproxy/ChunkedTransferTest.java

Server send events are send as chunked responses. The expectation is
that the chunks are immediately send and not buffered until the whole
response is done.
If a response is detected, the chunks are normally read and each read
chunk is immediately flushed, replicating the upstream behavior
downstream.

Supported chunked behavior for responses

---

CHANGES.md
src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
src/test/java/org/mitre/dsmiley/httpproxy/ChunkedTransferTest.java
src/test/java/org/mitre/dsmiley/httpproxy/ParallelConnectionsTest.java

When working with server send events I noticed, that connection issues were observed in the production environment. Two issues could be identified, that combine:
- apache http client limits the number of connections per route to 2 - as that value is never overwritten, this is the effective upper limit for parallel reverse proxy connections
- a connection, that is closed in the frontend does not cause the backing connection to be closed
Both conditions might have been problems already in the past, but they are less likely to be observed if only short lived http connections (small transfers, non-persistent connections).

Improved connection handling

---

CHANGES.md
src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
src/test/java/org/mitre/dsmiley/httpproxy/AcceptEncodingTest.java
src/test/java/org/mitre/dsmiley/httpproxy/ChunkedTransferTest.java

It was observed, that chunk encoded streams were not correctly passed
through the proxy servlet. Analysis showed, that the stream was gzip
compressed.
The issue is located in the Apache http client/JDK: if the stream from
client is compressed, apache http client will delegate to
GzipInputStream. The #available implementation of InflaterInputStream
(parent of GzipInputStream) returns 1 until EOF is reached.
This is not consistent with InputStream#available, which defines:
A single read or skip of this many bytes will not block, but may
read or skip fewer bytes.
To work around this, the optimization to check for available, a flush
is issued always.

Compressed, chunk encoded streams are not flushed immediately

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java

Casting `char` to `int` is redundant

---

README.md

After Spring Boot 2.x,RelaxedPropertyResolver may be cann't use,so add  an example

add example for springboot

---

src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java

I've recently encountered a situation where the proxy servlet was exposed on HTTP but where the external service was HTTPS. This all worked fine until that external service started returning cookies with the secure flag set. As it stands, the proxy servlet just copies this attribute but, in this scenario, to stop the cookies getting thrown away, the secure flag needs to be disabled. This is, of course, only applies where the servlet request is not accessed securely.
Note that there's no unit test for this as HttpUnit doesn't pass on the Secure attribute of Cookies.

Fixed Secure Cookie issue where the Proxy is accessible via HTTP.

---

CHANGES.md
README.md
src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java
src/test/java/org/mitre/dsmiley/httpproxy/ProxyServletTest.java

I have implemented the preserveCookiePath additional configuration parameter.
It allows the service under the proxy to seamlessly become a part of main site.
In practice I used it to share authentication cookie between distinct  parts of heterogeneous (Java + PHP) system.

preserveCookiePath configuration parameter support added.

---

CHANGES.md
pom.xml

Java 11 has been around a long time now; really we should require this at a major release boundary.

Require Java 11.  And bump build versions
